authapp/urls.py
from django.contrib import admin
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('update/', authapp.update, name='update'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
import mainapp.views as mainapp

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('my/admin/', include('adminapp.urls', namespace='my_admin')),
    path('auth/register/', include('social_django.urls', namespace='social')),
    path('orders/', include('ordersapp.urls', namespace='orders')),

    # path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.contrib import admin
from django.urls import path, re_path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    # path('', mainapp.index, name='index'),
    path('', mainapp.IndexView.as_view(), name='index'),
    # path('products/', mainapp.products, name='products'),

    re_path(r'^category/(?P<pk>\d+)/products/$',
            mainapp.category_products, name='category_products'),

    re_path(r'^category/(?P<pk>\d+)/products/(?P<page>\d+)/$',
            mainapp.category_products, name='category_products_pagination'),

    re_path(r'^product/(?P<pk>\d+)/$',
            mainapp.product_page, name='product_page'),

    # re_path(r'^product/(?P<pk>\d+)/$',
    #         mainapp.ProductDetailView.as_view(), name='product_page'),

    re_path(r'^product/detail/(?P<pk>\d+)/async/$',
            mainapp.product_detail_async),

    # path('contacts/', mainapp.contacts, name='contacts'),
    path('contacts/', mainapp.ContactsView.as_view(), name='contacts'),
]

ordersapp/urls.py
from django.contrib import admin
from django.urls import path, re_path
import ordersapp.views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='index'),
    path('order/create/', ordersapp.OrderCreate.as_view(), name='order_create'),
    path('order/update/<int:pk>/', ordersapp.OrderUpdate.as_view(), name='order_update'),
    path('order/delete/<int:pk>/', ordersapp.OrderDelete.as_view(), name='order_delete'),
    path('order/read/<int:pk>/', ordersapp.OrderRead.as_view(), name='order_read'),
    path('order/forming/complete/<int:pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),

]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField('имя категории', max_length=64)
    description = models.TextField('описание категории', blank=True)
    is_active = models.BooleanField(db_index=True, default=True)


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, verbose_name='категория продукта', on_delete=models.CASCADE)
    name = models.CharField('имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField('краткое описание', max_length=64, blank=True)
    desc = models.TextField('описание товара', blank=True)
    price = models.DecimalField('цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField('количество на складе', default=0)
    is_active = models.BooleanField(db_index=True, default=True)

    @staticmethod
    def get_active_items(self):
        return Product.objects.filter(category__is_active=True, is_active=True)

mainapp/views.py
from django.core.cache import cache
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from datetime import datetime
from django.views.generic import TemplateView, DetailView
from adminapp.views import PageTitleMixin
from geekshop.settings import LOW_CACHE
from mainapp.models import ProductCategory, Product

date = datetime.now()


# def index(request):
#     context = {
#         'page_title': 'Главная',
#         'year': date.year,
#     }
#     return render(request, 'mainapp/index.html', context)

def get_category(pk):
    if LOW_CACHE:
        key = f'productcategory_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(
                is_active=True,
                category__is_active=True
            ).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True,
                                      category__is_active=True).select_related('category')


def get_product(pk):
    if LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_in_productcategory(pk):
    if LOW_CACHE:
        key = f'products_in_productcategory_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(
                category__pk=pk, is_active=True,
                category__is_active=True)
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(
            category__pk=pk, is_active=True,
            category__is_active=True)


class IndexView(TemplateView):
    template_name = "mainapp/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['year'] = date.year
        context['page_title'] = 'Главная'
        return context


# def contacts(request):
#     context = {
#         'page_title': 'Контакты',
#         'year': date.year,
#     }
#     return render(request, 'mainapp/contacts.html', context)

class ContactsView(TemplateView):
    template_name = "mainapp/contacts.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['year'] = date.year
        context['page_title'] = 'Контакты'
        return context


# def products(request):
#     products = Product.objects.filter(is_active=True)
#
#     context = {
#         'page_title': 'Каталог',
#         'products': products,
#         'year': date.year,
#     }
#
#     return render(request, 'mainapp/products.html', context)


def category_products(request, pk, page=1):
    if pk == '0':
        category = {'pk': 0, 'name': 'Все'}
        # products = Product.objects.filter(is_active=True)
        products = get_products()
    else:
        # category = get_object_or_404(ProductCategory, pk=pk)
        category = get_category(pk)
        # products = category.product_set.filter(is_active=True)
        products = get_products_in_productcategory(pk)

    products_paginator = Paginator(products, 2)
    try:
        products = products_paginator.page(page)
    except PageNotAnInteger:
        products = products_paginator.page(1)
    except EmptyPage:
        products = products_paginator.page(products_paginator.num_pages)

    context = {
        'page_title': 'каталог',
        'products': products,
        'category': category,
    }
    return render(request, 'mainapp/category_products.html', context)


def product_page(request, pk):
    # product = get_object_or_404(Product, pk=pk)
    product = get_product(pk)
    context = {
        'page_title': 'каталог',
        'category': product.category,
        'product': product,
    }

    return render(request, 'mainapp/product_detail.html', context)

# class ProductDetailView(DetailView, PageTitleMixin, ):
#     model = Product
#     pk_url_kwarg = 'pk'


def product_detail_async(request, pk):
    if request.is_ajax():
        try:
            # product = Product.objects.get(pk=pk)
            product = get_product(pk)
            return JsonResponse({
                'product_price': product.price,
            })
        except Exception as e:
            return JsonResponse({
                'error': str(e),
            })


def get_menu():
    if LOW_CACHE:
        key = 'catalog_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)

mainapp/templates/mainapp/includes/inc__category_menu.html
<div class="catalogMenu clearfix">
    <ul>
        <li>
            <a href="{% url 'main:category_products' 0 %}"
               class="{% if request.resolver_match.kwargs.pk == '0' %} active {% endif %}">
                Все
            </a>
        </li>
        {% for category in categories %}
            <li>
                <a href="{% url 'main:category_products' category.pk %}"
                class="{% if request.resolver_match.kwargs.pk|add:0 == category.pk %} active {% endif %}">
                    {{ category.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
</div>

mainapp/templates/mainapp/includes/inc__main_menu.html
{% load static %}
<div class="header"><span class="name">Kingsman</span> <span
        class="slogan">Одежда для настоящих джентельменов</span>
    <img width="90" class="logo" src="{% static 'img/logo.png' %}" alt="">
    <ul class="main_menu">
        <li><a href="{% url 'main:index' %}" {% if request.path == '/' %} class="active_link" {% endif %}>Главная</a>
        </li>
        <li>
            <a href="{% url 'main:category_products' 0 %}"
                    {% if request.path == '/products/' %}
               class="active_link"
                    {% endif %}>Каталог</a>
        </li>
        <li><a href="{% url 'main:contacts' %}" {% if request.path == '/contacts/' %} class="active_link" {% endif %}>Контакты</a>
        </li>
        {% if user.is_authenticated %}
            <li>
                <div class="dropdown">
                    <a class="dropdown-toggle" href="" data-toggle="dropdown">
                        {{ user.first_name|default:'пользователь'|title }}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{% url 'auth:update' %}">
                                профиль
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'ordersapp:index' %}">
                                заказы
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
                <a href="{% url 'auth:logout' %}">
                    Выход
                </a>
            {% else %}
                <a href="{% url 'auth:login' %}">
                    Вход
                </a>
            {% endif %}
        </li>
        <li>
            {% if user.is_authenticated %}
                <li>
                    {% if basket %}
                        <a href="{% url 'basket:index' %}">
                        <span>
                                {{ basket.0.total_cost|floatformat:0 }} руб ({{ basket.0.total_quantity }} шт)
                        </span>
                        </a>
                    {% endif %}
                </li>
            {% endif %}
        </li>
        <li>
            {% if user.is_superuser %}
                <a href="{% url 'my_admin:index' %}">
                    <span>
                        Админка
                    </span>
                </a>
            {% endif %}
        </li>
    </ul>
</div>