authapp/urls.py
from django.contrib import admin
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('update/', authapp.update, name='update'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.contrib import admin
from django.urls import path, re_path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.index, name='index'),
    path('add/product/<int:pk>/', basketapp.add_product, name='add_product'),
    path('delete/product/<int:pk>/', basketapp.delete_product, name='delete_product'),
    path('change/<int:pk>/quantity/<int:quantity>/', basketapp.change),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
import mainapp.views as mainapp

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('my/admin/', include('adminapp.urls', namespace='my_admin')),
    path('auth/register/', include('social_django.urls', namespace='social')),
    path('orders/', include('ordersapp.urls', namespace='orders')),

    # path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.contrib import admin
from django.urls import path, re_path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    # path('', mainapp.index, name='index'),
    path('', mainapp.IndexView.as_view(), name='index'),
    # path('products/', mainapp.products, name='products'),

    re_path(r'^category/(?P<pk>\d+)/products/$',
            mainapp.category_products, name='category_products'),

    re_path(r'^category/(?P<pk>\d+)/products/(?P<page>\d+)/$',
            mainapp.category_products, name='category_products_pagination'),

    re_path(r'^product/(?P<pk>\d+)/$',
            mainapp.product_page, name='product_page'),

    # re_path(r'^product/(?P<pk>\d+)/$',
    #         mainapp.ProductDetailView.as_view(), name='product_page'),

    re_path(r'^product/detail/(?P<pk>\d+)/async/$',
            mainapp.product_detail_async),

    # path('contacts/', mainapp.contacts, name='contacts'),
    path('contacts/', mainapp.ContactsView.as_view(), name='contacts'),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField('имя категории', max_length=64)
    description = models.TextField('описание категории', blank=True)
    is_active = models.BooleanField(db_index=True, default=True)


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, verbose_name='категория продукта', on_delete=models.CASCADE)
    name = models.CharField('имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField('краткое описание', max_length=64, blank=True)
    desc = models.TextField('описание товара', blank=True)
    price = models.DecimalField('цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField('количество на складе', default=0)
    is_active = models.BooleanField(db_index=True, default=True)

    @staticmethod
    def get_active_items(self):
        return Product.objects.filter(category__is_active=True, is_active=True)

mainapp/views.py
from django.core.cache import cache
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from datetime import datetime
from django.views.generic import TemplateView, DetailView
from adminapp.views import PageTitleMixin
from geekshop.settings import LOW_CACHE
from mainapp.models import ProductCategory, Product

date = datetime.now()


# def index(request):
#     context = {
#         'page_title': 'Главная',
#         'year': date.year,
#     }
#     return render(request, 'mainapp/index.html', context)

def get_category(pk):
    if LOW_CACHE:
        key = f'productcategory_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(
                is_active=True,
                category__is_active=True
            ).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True,
                                      category__is_active=True).select_related('category')


def get_product(pk):
    if LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_in_productcategory(pk):
    if LOW_CACHE:
        key = f'products_in_productcategory_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(
                category__pk=pk, is_active=True,
                category__is_active=True)
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(
            category__pk=pk, is_active=True,
            category__is_active=True)


class IndexView(TemplateView):
    template_name = "mainapp/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['year'] = date.year
        context['page_title'] = 'Главная'
        return context


# def contacts(request):
#     context = {
#         'page_title': 'Контакты',
#         'year': date.year,
#     }
#     return render(request, 'mainapp/contacts.html', context)

class ContactsView(TemplateView):
    template_name = "mainapp/contacts.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['year'] = date.year
        context['page_title'] = 'Контакты'
        return context


# def products(request):
#     products = Product.objects.filter(is_active=True)
#
#     context = {
#         'page_title': 'Каталог',
#         'products': products,
#         'year': date.year,
#     }
#
#     return render(request, 'mainapp/products.html', context)


def category_products(request, pk, page=1):
    if pk == '0':
        category = {'pk': 0, 'name': 'Все'}
        # products = Product.objects.filter(is_active=True)
        products = get_products()
    else:
        # category = get_object_or_404(ProductCategory, pk=pk)
        category = get_category(pk)
        # products = category.product_set.filter(is_active=True)
        products = get_products_in_productcategory(pk)

    products_paginator = Paginator(products, 2)
    try:
        products = products_paginator.page(page)
    except PageNotAnInteger:
        products = products_paginator.page(1)
    except EmptyPage:
        products = products_paginator.page(products_paginator.num_pages)

    context = {
        'page_title': 'каталог',
        'products': products,
        'category': category,
    }
    return render(request, 'mainapp/category_products.html', context)


def product_page(request, pk):
    # product = get_object_or_404(Product, pk=pk)
    product = get_product(pk)
    context = {
        'page_title': 'каталог',
        'category': product.category,
        'product': product,
    }

    return render(request, 'mainapp/product_detail.html', context)

# class ProductDetailView(DetailView, PageTitleMixin, ):
#     model = Product
#     pk_url_kwarg = 'pk'


def product_detail_async(request, pk):
    if request.is_ajax():
        try:
            # product = Product.objects.get(pk=pk)
            product = get_product(pk)
            return JsonResponse({
                'product_price': product.price,
            })
        except Exception as e:
            return JsonResponse({
                'error': str(e),
            })


def get_menu():
    if LOW_CACHE:
        key = 'catalog_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)

mainapp/templates/mainapp/base.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {% block title %} {{ page_title|title }} {% endblock %} </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}
</head>

<body>
<div class="container"> {% block bodyContent %} {% endblock %} {% block footer %}
    <div class="footer clearfix">
        <p class="rights">&copy; Все права защищены {{ year }} год</p>
    </div> {% endblock %} </div>
</body>

</html>

mainapp/templates/mainapp/catalog.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block bodyContent %}
    {% include 'mainapp/includes/inc__main_menu.html' %}
    <h1 class="headline">Каталог</h1>
    {% include 'mainapp/includes/inc__category_menu.html' %}
    <div style="margin: 0 auto;">
        {% for product in products %}
            <div class="productCell">
                <span> {{ product.name }} </span>
                <img width="300px" height="400px" src="{{ product.image.url }}" alt="#">
                <span>Цена {{ product.price }} руб.</span>
            </div>
        {% endfor %}
    </div>

{% endblock %}

mainapp/templates/mainapp/category_products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block bodyContent %}
    {% include 'mainapp/includes/inc__main_menu.html' %}
    <h1 class="headline">Каталог</h1>
    {% include 'mainapp/includes/inc__category_menu.html' %}
    <div class="related">
        <div class="title clearfix">
            <h2 style="color: whitesmoke; text-align: center">Продукты в категории {{ category.name|title }}</h2>
            <div class="paginator">
                {% if products.has_previous %}
                    <a href="{% url 'main:category_products_pagination' category.pk products.previous_page_number %}">
                        <
                    </a>
                {% endif %}
                <span class="current">страница {{ products.number }} из {{ products.paginator.num_pages }}</span>
                {% if products.has_next %}
                    <a href="{% url 'main:category_products_pagination' category.pk products.next_page_number %}">
                        >
                    </a>
                {% endif %}
            </div>
        </div>

        <div class="productList">
            {% comment %}{% for product in products %}
                    <div class="block">
                        <a href="{% url 'basket:add_product' product.pk %}">
                            <img src="/media/{{ product.image }}" alt="">
                            <div class="text">
                                <img src="/static/img/icon-hover.png" alt="img">
                                <h4>{{ product.name }}</h4>
                                <p>{{ product.short_desc }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}{% endcomment %}
            {% for product in products %}
                <div class="productCell">
                    <span> {{ product.name }} </span>
                    <a href="{% url 'mainapp:product_page' product.pk %}">
                        <img width="300px" height="400px" src="{{ product.image.url }}" alt="#">
                    </a>
                    <span>Цена {{ product.price }} руб.</span>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block bodyContent %}
    {% include 'mainapp/includes/inc__main_menu.html' %}
    <h1 class="headline">Наши контакты</h1>
    <div class="contacts">
        <form class="form" action="">
            <fieldset>
                <legend>Мы вам перезвоним! Заполните форму ниже:</legend>
                Ваше имя:
                <input type="text" placeholder="Введите ваше имя">
                <br> Ваш номер телефона:
                <input type="telephone" placeholder="Введите номер">
                <br>
                <input type="submit" value="Отправить">
                <input type="reset" value="Сбросить"></fieldset>
        </form>
    </div>
    <div class="map_desc">
        <h3>Вы можете нас найти по адресу г.Омск, улица Гагарина 14, 4 этаж.</h3>
        <iframe style="width: 100%;"
                src="https://yandex.ru/map-widget/v1/?um=constructor%3A18fa8629dad96b908aa43cc9c6089cb670ae4d57d38054948fd8bda39b4b04dc&amp;source=constructor"
                width="657" height="609" frameborder="0"></iframe>
    </div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block bodyContent %}
    {% include 'mainapp/includes/inc__main_menu.html' %}
    <div class="slider">
        <img class="slider_pic" src="{% static 'img/slider3.jpg' %}" alt="">
        <span class="description">Добро пожаловать в магазин модной классической мужской одежды!</span>
    </div>
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %} {% load static %} {% block bodyContent %}
    {% include 'mainapp/includes/inc__main_menu.html' %} {% include 'mainapp/includes/inc__category_menu.html' %}
    {% load my_tags %}
    <div class="productPage">
        <div class="details-slider">
            <div class="productImage"><img style="width: 300px;height:400px ;"
                                           src="{{ product.image|media_folder_products }}"
                                           alt="{{ product.short_desc }}"></div>
            <div class="productInfo">
                <h3 style="color: whitesmoke; font-size: 40px">{{ product.name }}</h3>
                <p style="color: whitesmoke; font-size: 30px; display: block;
                   margin-left: 60px;"> {{ product.price }} <span>руб</span></p>
                <a class="buttons" href="{% url 'basket:add_product' product.pk %}">
                    Заказать
                </a>
            </div>
        </div>
    </div> {% endblock %}

mainapp/templates/mainapp/product_detail.html
{% extends 'mainapp/base.html' %} {% load static %} {% block bodyContent %}
    {% include 'mainapp/includes/inc__main_menu.html' %} {% include 'mainapp/includes/inc__category_menu.html' %}
    {% load my_tags %}
    <div class="productPage">
        <div class="details-slider">
            <div class="productImage"><img style="width: 300px;height:400px ;"
                                           src="{{ product.image|media_folder_products }}"
                                           alt="{{ product.short_desc }}"></div>
            <div class="productInfo">
                <h3 style="color: whitesmoke; font-size: 40px">{{ product.name }}</h3>
                <p style="color: whitesmoke; font-size: 30px; display: block;
                   margin-left: 60px;"> {{ product.price }} <span>руб</span></p>
                <a class="buttons" href="{% url 'basket:add_product' product.pk %}">
                    Заказать
                </a>
            </div>
        </div>
    </div> {% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block bodyContent %}
    {% include 'mainapp/includes/inc__main_menu.html' %}
    <h1 class="headline">Каталог</h1>
    {% include 'mainapp/includes/inc__category_menu.html' %}
    <div class="productList">
        {% for product in products %}
            <div class="productCell">
                <span> {{ product.name }} </span>
                <a href="{% url 'mainapp:product_page' product.pk %}">
                    <img width="300px" height="400px" src="{{ product.image.url }}" alt="#">
                </a>
                <span>Цена {{ product.price }} руб.</span>
            </div>
        {% endfor %}
    </div>

{% endblock %}